import '@/styles/globals.css';

import type { Metadata } from 'next';
import { Poppins, Raleway } from 'next/font/google';
import { PropsWithChildren } from 'react';

import { cn } from '@/lib/utils';

const raleway = Raleway({
  subsets: ['latin'],
  variable: '--heading-font',
});

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--body-font',
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body className={cn('font-body flex min-h-screen flex-col', raleway.variable, poppins.variable)}>{children}</body>
    </html>
  );
};

export default RootLayout;
