name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Login step only executed for pushes to main
      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_Token }}

      # Build and tag the production Docker image
      - name: Build the production Docker image
        run: |
          docker build . --file Dockerfile --target runner --tag ghcr.io/${{ github.repository }}:${{ github.sha }}
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:latest
          fi

      # Build and tag the development Docker image
      - name: Build the development Docker image
        run: |
          docker build . --file Dockerfile --target dev --tag ghcr.io/${{ github.repository }}:${{ github.sha }}-dev
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            docker tag ghcr.io/${{ github.repository }}:${{ github.sha }}-dev ghcr.io/${{ github.repository }}:dev
          fi

      # Push the production Docker image
      - name: Push the production Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}:latest

      # Push the development Docker image
      - name: Push the development Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}-dev
          docker push ghcr.io/${{ github.repository }}:dev
